requirements:
  # Common requirements for all containers (including pipelines)
  common:
    - astropy: 5.2.2
    - Flask: 3.0.3
    - psycopg2-binary: 2.9.9
    - requests: 2.32.2

  backend:
    - docker: 7.1.0
    - Flask-RESTful: 0.3.10
    - gunicorn: 20.1.0
    - redis: 5.0.4

  frontend:
    - matplotlib: 3.7.1
    - numpy: 1.24.3
    - streamlit: 1.35.0
  
  # Dynamic pipeline requirements
  pipelines:
    # Common requirements for all pipelines
    common:
      - numpy: 1.24.3
      - tqdm: 4.66.4

    augment:
      - scikit-image: 0.21.0
      - scipy: 1.10.1

    fetch:

    radon:
      - scipy: 1.10.1
